### ISSUE TITLE
avalonia-amd-gen doesn't read properties in csproj

### ISSUE THREAD

**Issue by philippelatulippe** [AvaloniaUI/Avalonia.Markup.Declarative#68]
When I run avalonia-amd-gen on a project created by Rider, I get the following error:

```
Packages found in the .csproj file:
An error occurred: '$(AvaloniaVersion)' is not a valid version string. (Parameter 'value')
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at AvaloniaExtensionGenerator.CsProjectTypesExtractor.GetAllDependencyPackages(String packageName, String packageVersion, String targetFramework) in C:\Projects\Avalonia\Avalonia.Markup.Declarative\src\AvaloniaExtensionGenerator\CsProjectTypesExtractor.cs:line 80
   at AvaloniaExtensionGenerator.CsProjectTypesExtractor.LoadTypesFromProject(String projectPath, String baseTypeNameToFilter, String[] ignoreAssemblies) in C:\Projects\Avalonia\Avalonia.Markup.Declarative\src\AvaloniaExtensionGenerator\CsProjectTypesExtractor.cs:line 147
   at AvaloniaExtensionGenerator.Program.Main(String[] args) in C:\Projects\Avalonia\Avalonia.Markup.Declarative\src\AvaloniaExtensionGenerator\Program.cs:line 73
```

It looks like the csproj file reader doesn't understand variables, since the variable `AvaloniaVersion` is definited in `PropertyGroup`.

**Comment by gritsenko** [comment]
@philippelatulippe can you share archive with the project folder here?

**Comment by philippelatulippe** [comment]
I can't share the whole project but I can certainly share the csproj:

<details><summary>csproj</summary>
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AvaloniaVersion>11.2.0-rc1</AvaloniaVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Markup.Declarative" Version="11.2.0-beta4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Svg.Skia" Version="11.1.0.1" />
        <PackageReference Include="FluentAvaloniaUI" Version="2.1.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
    
</Project>
</details>

**Comment by IvanJosipovic** [comment]
@gritsenko, I'm starting to wonder if integrating the generation CLI into MSBuild would make it simpler. A Custom MSbuild step could get a list of all loaded libraries and that could be used to trigger the project.

**Comment by gritsenko** [comment]
@IvanJosipovic I thought about it as well, but we need to generate extensions **before** building step already, and even when project itself has errors and can't to be built. Do you think it is possible to use msbuild in this case? Or I misunderstanding how it works?

**Comment by IvanJosipovic** [comment]
> @IvanJosipovic I thought about it as well, but we need to generate extensions **before** building step already, and even when project itself has errors and can't to be built. Do you think it is possible to use msbuild in this case? Or I misunderstanding how it works?

@gritsenko, I created an example PR, https://github.com/AvaloniaUI/Avalonia.Markup.Declarative/pull/70
Have a look, if its interesting, we can continue the work there. I believe we can also publish custom "MSBuild Target" as a part of the NuGet package to make it even simpler to use.

**Comment by gritsenko** [comment]
I tried to create new avalonia app with rider and it looks like they removed that variable from csproj. So it's not critical anymore
